/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_eduardozils.screens;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import trabalho_eduardozils.DAO.CarroDAO;
import trabalho_eduardozils.DAO.ClienteDAO;
import trabalho_eduardozils.DAO.VendaDAO;
import trabalho_eduardozils.DAO.VendedorDAO;
import trabalho_eduardozils.model.Venda;
import trabalho_eduardozils.model.DateUtil;

/**
 *
 * @author eduar
 */
public class TelaInicial extends javax.swing.JDialog {

    VendaDAO vendaDAO = new VendaDAO();
    CarroDAO carroDAO = new CarroDAO();
    VendedorDAO vendedorDAO = new VendedorDAO();
    ClienteDAO clienteDAO = new ClienteDAO();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        carregaTable(vendaDAO.getAll());
        attHora();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btCadVendedores = new javax.swing.JButton();
        btCadClientes = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        rbCodigo = new javax.swing.JRadioButton();
        tfPesquisa = new javax.swing.JTextField();
        btPesquesaFiltro = new javax.swing.JButton();
        btLimpaFiltro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbValor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Concesionaria Katchow");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Concesionaria Katchow");

        btCadVendedores.setText("Cadastro de Vendedores");
        btCadVendedores.setToolTipText("Cadastrar um novo funcionario(a)");
        btCadVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadVendedoresActionPerformed(evt);
            }
        });

        btCadClientes.setText("Cadastro de Clientes");
        btCadClientes.setToolTipText("Efetuar cadastros de novos clientes");
        btCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadClientesActionPerformed(evt);
            }
        });

        btVenda.setText("Nova venda");
        btVenda.setToolTipText("Efetuar uma nova venda");
        btVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Carro", "Cliente", "Valor", "Funcionario", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tabela);

        jLabel2.setText("Relação de vendas efetuadas");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton4.setText("Cadastrar carro");
        jButton4.setToolTipText("Efetuar cadastro de um novo carro");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Filtro");

        buttonGroup1.add(rbCodigo);
        rbCodigo.setSelected(true);
        rbCodigo.setText("Codigo");

        tfPesquisa.setToolTipText("Informe a chave de sua pesquisa");

        btPesquesaFiltro.setText("Pesquisar 🔎");
        btPesquesaFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquesaFiltroActionPerformed(evt);
            }
        });

        btLimpaFiltro.setText("Limpar Pesquisa");

        jLabel4.setText("jLabel4");

        buttonGroup1.add(rbValor);
        rbValor.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCadVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(btCadClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(rbCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(rbValor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btPesquesaFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLimpaFiltro))
                            .addComponent(tfPesquisa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCadVendedores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btCadClientes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbCodigo)
                                            .addComponent(rbValor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btPesquesaFiltro)
                                            .addComponent(btLimpaFiltro))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaActionPerformed
        this.dispose();
        CadastroVenda dialog = null;
        try {
            dialog = new CadastroVenda(new javax.swing.JFrame(), true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btVendaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        CadastroCarro dialog = null;
        try {
            dialog = new CadastroCarro(new javax.swing.JFrame(), true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btCadVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadVendedoresActionPerformed
        this.dispose();
        CadastroVendedor dialog = null;
        try {
            dialog = new CadastroVendedor(new javax.swing.JFrame(), true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setVisible(true);

    }//GEN-LAST:event_btCadVendedoresActionPerformed

    private void btCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadClientesActionPerformed
        this.dispose();
        CadastroCliente dialog = null;
        try {
            dialog = new CadastroCliente(new javax.swing.JFrame(), true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        dialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadClientesActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        attHora();        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void btPesquesaFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquesaFiltroActionPerformed
        filtrar();        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquesaFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaInicial dialog = null;
                try {
                    dialog = new TelaInicial(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadClientes;
    private javax.swing.JButton btCadVendedores;
    private javax.swing.JButton btLimpaFiltro;
    private javax.swing.JButton btPesquesaFiltro;
    private javax.swing.JButton btVenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbValor;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
 private void carregaTable(List<Venda> listaVenda) {
        if (listaVenda == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0);
        for (Venda f : listaVenda) {
            model.addRow(new Object[]{f.getCodigo(), f.getCodigo_carro(), f.getCodigo_cliente(), f.getValorTotal(), f.getCodigo_vendedor(), f.getData_venda()});
        }
    }

    private void attHora() {
        String data = "";
        data = DateUtil.dateToStringHora(new Date());
        jLabel4.setText(data);
    }

    private void filtrar() {
        try {
            if (rbCodigo.isSelected() && tfPesquisa.getText().trim().length() != 0) {
                Venda venda = vendaDAO.getById(Integer.parseInt(tfPesquisa.getText()));
                List<Venda> vendaList = new ArrayList<>();
                vendaList.add(venda);
                carregaTable(vendaList);
            } else if (rbValor.isSelected() && tfPesquisa.getText().trim().length() != 0) {
                carregaTable(vendaDAO.getByName(tfPesquisa.getText()));
            } else {
                carregaTable(vendaDAO.getAll());
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
